### PR TITLE
Fixing Bigtable HBase 2 tests.

### PR DESCRIPTION
**Pull request by sduskis**

### CODE REVIEW

**Comment by spollapally** [comment]
I see couple of new method impls including enableTable, but I didn't follow the fixed test case. Is the commit missing any files?

**Comment by sduskis** [comment]
I'll add tests for enable/disable :)

**Comment by sduskis** [comment]
There are two fixes:

1. Use the correct Preconditions class so that the HBase MiniCluster test passes.  The HBase Minicluster does not have the hbase shaded version of Preconditions in the classpath
2. Implement the version of createTable used by by some of the new tests.

**Comment by sduskis** [comment]
@spollapally, I made a significant change to enable/disable table.  Can you please take another look?

**Comment by spollapally** [comment]
Changes look good. I vaguely remember Hbase impl not throwing exceptions for negative cases - when disabling or enabling tables already in that state. We should see if these are passing the Hbase integration tests, if you haven't yet.

**Comment by sduskis** [comment]
HBase 2 tests are in a really bad state right now.  I'm going to merge this PR, and try to fix the HBase tests in another PR.

**Comment by spollapally** [comment]
Ok

**Pull request merged**
