### PR TITLE
Excluding older guava versions in the root pom.xml.

### PR DESCRIPTION
**Pull request by sduskis**
Explicitely relying on guava 13 for the integration tests.

### CODE REVIEW

**Comment by sduskis** [comment]
FYI, both the hbase minicluster and bigtable integration tests pass.

**Comment by AngusDavis** [comment]
First, I agree on the java5 exclude. Second, questions:
1) Would it be better to have a direct dependency on guava ${guava.version} to override the hadoop/hbase dependency? (and keep the guava 13 in integration tests)
2) If not, it seems that having excludes might be prone to things sneaking in again in the future. Consider using: http://maven.apache.org/enforcer/enforcer-rules/bannedDependencies.html to ban guava versions less than 18 [,18.0]

**Comment by sduskis** [comment]
1) I'm not sure where you mean.  We already have a dependency on guava 18.0 in bigtable-hbase.  We shade in that dependency in bigtable-hbase-1.0.  We need guava 13 in integration tests.  I'm not sure how ${guava.version} helps us in this case.  What problem does ${guava.version} solve?

2) good idea.  I'll add it to bigtable-hbase-1.0 and -1.1.

**Comment by sduskis** [comment]
Oh, I see.  It makes sense to add a ${guava.version} so it's consistent between the inclusion and the bannedDependenies plugin

**Comment by AngusDavis** [comment]
For 1) - if the hbase-1.0 and hbase-1.1 jars depend directly on guava, then the version they reference will win for the purposes of dependency resolution. At that point, excludes are probably not required.
LGTM, anyways. Feel free to modify or not.

**Comment by sduskis** [comment]
Ugh.  I forgot to rebase -i master first.  Sorry.

**Pull request merged**
