### PR TITLE
Making the shaded artifacts the main one rather than a classifier.

### PR DESCRIPTION
**Pull request by sduskis**

### CODE REVIEW

**Comment by AngusDavis** [comment]
Could you add comments on these so they don't get flipped back? More or less copying some of the points from the email thread on why it's required.

**Comment by sduskis** [comment]
Comments added.

**Comment by sduskis** [comment]
@AngusDavis: How do the comments look?

**Comment by AngusDavis** [comment]
It would be great if you could include mention of which artifacts /  packages clash so that in a year or two when HBase upgrades proto / netty, we'll know it's OK to re-instate the non-shaded artifacts.

**Comment by sduskis** [comment]
@AngusDavis: good point.  I udpates the comments.

**Comment by AngusDavis** [comment]
LGTM

**Pull request merged**
