### PR TITLE
Increase junit timeout for IntegrationTests

### PR DESCRIPTION
**Pull request by kevinsi4508**
Increase junit timeout for IntegrationTests from 10 minutes to 30.

### CODE REVIEW

**Comment by sduskis** [comment]
The 10 minutes limit is needed for most cases.  Can  you please use a different mechanism to make this work, like a system parameter to make this work instead of a hard coded 30 minutes?

**Comment by kevinsi4508** [comment]
That parameter was hardcoded.  I am trying make the test go through first and then will think of a better way.

**Comment by sduskis** [comment]
This change potentially invalidates the current configuration of our integration tests.  We need to revert this change.

**Comment by kevinsi4508** [comment]
Why would increasing the junit timeout invalidates the configuration of the integration tests? Can you provide details? Thanks!

**Comment by sduskis** [comment]
We have to take this offline.

**Pull request merged**
