### PR TITLE
Use DEFAULT_STREAMING_BATCH_SIZE for streamingBatchSize

### PR DESCRIPTION
**Pull request by ianzhou1**
Instead of DEFAULT_STREAMING_BUFFER_SIZE

### CODE REVIEW

**Comment by ianzhou1** [comment]
I signed it! Google employee (ianzhou@google.com)

**Comment by sduskis** [comment]
I signed it!

**Comment by sduskis** [comment]
@ianzhou1 Can you please comment with just "I signed it!"?  The cla is still showing up as no.

**Comment by ianzhou1** [comment]
I signed it!

**Pull request merged**
