### PR TITLE
#1691 Remove duplication across hbase1 and hbase2 integration tests

### PR DESCRIPTION
**Pull request by arkash**
@sduskis please review refactored TestSanpshots for duplication as per #1691

### CODE REVIEW

**Comment by sduskis** [comment]
After the CLA is signed, I think that there only needs to be one TestSnapshots class.  I don't think we need the HBase 1 vs. HBase 2 implementation.  We'll set our parameters correctly on our Jenkins tests.

**Comment by arkash** [comment]
@sduskis merged and moved TestSnapshots to common hbase. Checked why CLA is still failing.

**Comment by sduskis** [comment]
@arkash can you please add a comment that says "I signed it!"?

**Comment by arkash** [comment]
I signed it!

**Comment by sduskis** [comment]
Did you sign the CLA?

**Comment by arkash** [comment]
@sduskis my account is locked working on getting it fixed

**Pull request closed without merging**
