### PR TITLE
User can configure a Credentials Callable.

### PR DESCRIPTION
**Pull request by sduskis**

### CODE REVIEW

**Comment by sduskis** [comment]
This is an attempt to fix #1895

**Comment by igorbernstein2** [comment]
I dont love this approach: it's adding yet another layer of indirection. At the end of the day we need a `Credentials` instance. `GoogleCredentials` already (de)serializes json and dispatches to both `UserCredentials`,  `ServiceAccountCredentials`. On top of that we have `CredentialFactory` that dispatches to `GoogleCredentials` from `CredentialOptions` from various sources. This will add yet another dispatcher to the mix. I would prefer to simplify the current system then add another knob to it

**Comment by sduskis** [comment]
@igorbernstein2: Ack.  Indirection is quite bad in this case.

In #1895, A user requested some way to use the same `Credentials` object for multiple clients. Right now, the only published option for CBT is the HBase API where the user interface is a `Map<String, String>`. 

There are a few ways to get a `Credentials` that we discussed on #1895:

1. We can add a new constructor to our HBase `Connection` objects, and potentially add wrappers in `BigtableConfiguration`.
2. We can use a level of indirection with `String`s like we did here.
3. We can do some other well known `Singleton` type thing.

Do you have any better ideas about how to implement this in the short term?

**Comment by igorbernstein2** [comment]
I think it might be easier to discuss in person, but I would love to deprecate the `CredentialOption` indirection step, have BigtableOptions expose `Credentials` directly, and have the hbase config encode the `GoogleCredentials` json format.

**Comment by sduskis** [comment]
Closing this PR in favor of #1900

**Pull request closed without merging**
