### PR TITLE
Upgrading grpc to 1.4.0

### PR DESCRIPTION
**Pull request by sduskis**

### CODE REVIEW

**Comment by igorbernstein2** [comment]
Don't forget to bump tcnative to 2.0.1-Final

**Comment by sduskis** [comment]
Ugh.  We have a not backwards compatible change on our hands.  Older versions of grpc are not compatible with  tcnative to 2.0.1-Final.

**Comment by igorbernstein2** [comment]
Maybe we should hold off upgrading grpc until https://github.com/grpc/grpc-java/pull/2485 lands?

**Comment by sduskis** [comment]
This should fix #1382, if and when this is complete.

It turns out that the grpc upgrade can use older versions of netty, so I'll remove the netty upgrade and keep grpc and protobuf upgrades.

**Pull request merged**
