### PR TITLE
Update the number of rows need to be returned on rescan

### PR DESCRIPTION
**Pull request by kevinsi4508**
Update the number of rows need to be returned by removing the number of rows that are already read from the original page limit.

### CODE REVIEW

**Comment by kevinsi4508** [comment]
ping

**Comment by sduskis** [comment]
We need to discuss this in person.  I don't think I can do a review of this CL without that.

**Comment by kevinsi4508** [comment]
Sure, we can discuss this in person. BTW, this PR is a fix for a bug discovered when working on WhileMatchFilter.

**Comment by kevinsi4508** [comment]
As discussed offline. I updated the code to keep track of row count and not resetting it. Plus we check if rescan would result in the number rows read over the page limit.
PTAL

**Comment by sduskis** [comment]
LGTM (after squashing commits)

**Pull request merged**
