### PR TITLE
Attach the shaded artifacts instead of replacing the main artifact

### PR DESCRIPTION
**Pull request by AngusDavis**

### CODE REVIEW

**Comment by AngusDavis** [comment]
Tested with bigtable and hbase mini cluster integration-tests.

**Comment by sduskis** [comment]
LGTM

**Comment by AngusDavis** [comment]
Solomon - Are there any release scripts that I should update to look for a -shaded.jar before merging?

**Comment by sduskis** [comment]
There some stuff in jenkins that would have to be fixed after the merge.  I'll take care of it.  The "release" is more of a manual process right now.

**Comment by sduskis** [comment]
Feel free to merge... I'll fix Jenkins.

**Comment by AngusDavis** [comment]
Sgtm. Merging.

**Pull request merged**
