### PR TITLE
Some refactoring for HBase 2

### PR DESCRIPTION
**Pull request by sduskis**
- Creating a new AbstractBigtableTable, since HBase has new Table methods.
- Creating a new BigtableTable in hbase2
- Using non-deprecated methods and classes
- Moving around Admin methods to show which ones should be implemented

### CODE REVIEW

**Comment by spollapally** [comment]
Changes look good. What tests were failing? I didn't notice any failures.

**Comment by sduskis** [comment]
`TestCheckAndMutate` uses the old methods for checkAnd*.  I updated it to use the new methods, which were not implemented, and that's when tests failed.  I backed out that change so that I could get this large PR in place.

**Comment by spollapally** [comment]
Seeing this error after the merge with "mvn clean install -U". Can you try
if you see the same?

[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile
(default-testCompile) on project bigtable-hbase: Compilation failure
[ERROR]
/Users/S.Pollapally/ecl-ws/cbt-sol/bigtable-hbase-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/TestBigtableTable.java:[115,13]
com.google.cloud.bigtable.hbase.AbstractBigtableTable is abstract; cannot
be instantiated

**Comment by sduskis** [comment]
It's strange that travis passed.

**Comment by sduskis** [comment]
I'll fix it.

**Pull request merged**
