### PR TITLE
expose app profiles in beam

### PR DESCRIPTION
**Pull request by igorbernstein2**

### CODE REVIEW

**Comment by sduskis** [comment]
I don't think that we need this.  The import tool should remain as simple as possible.  Users can write a bit of code if they really know what they're doing with App Profiles.

**Comment by igorbernstein2** [comment]
As it stands the sequence file reading & writing code is vendored in the importer and I don't want to encourage our users to use it (just yet). So it's not really feasible for users write their own sequence file pipelines just to specify an app profile

**Comment by sduskis** [comment]
The app profile id should not be needed for the import tool.  The import tool is meant to populate the cluster from scratch.  I don't see why we can't just use the default app_id. 

We should talk offline to see if there's anything I'm missing here.

**Comment by mbrukman** [comment]
Can the import tool be used to bulk import a large new table to an existing serving cluster? Wouldn't app profiles be useful in that case to direct traffic to a particular cluster?

**Pull request merged**
