### PR TITLE
Turn on cached channel pooling by default

### PR DESCRIPTION
**Pull request by rupeshitpatekarq**
Rebase with BigtableOptions fixes & removed null credential condition as its not needed now.

### CODE REVIEW

**Comment by rupeshitpatekarq** [comment]
In TestAppProfile.java -> setup() 

BigtableOptions opts = new BigtableOptions.Builder()
        .setDataHost("localhost")
        .setAdminHost("locahost")
        .setPort(port)
        .setProjectId("fake-project")
        .setInstanceId("fake-instance")
        .setUserAgent("fake-agent")
        .setUsePlaintextNegotiation(true)
        **.setUseCachedDataPool(false)**
        .setCredentialOptions(CredentialOptions.nullCredential())
        .build();

If I won't set useCachedDataPool value to false then I am receiving following exception:

INFO: Bigtable options: BigtableOptions{dataHost=localhost, adminHost=locahost, projectId=fake-project, instanceId=fake-instance, appProfileId=my-app-profile, userAgent=fake-agent, credentialType=None, port=41019, dataChannelCount=16, retryOptions=RetryOptions{retriesEnabled=true, allowRetriesWithoutTimestamp=false, statusToRetryOn=[UNAVAILABLE, ABORTED, UNAUTHENTICATED, DEADLINE_EXCEEDED], initialBackoffMillis=5, maxElapsedBackoffMillis=60000, backoffMultiplier=2.0, streamingBufferSize=60, readPartialRowTimeoutMillis=60000, maxScanTimeoutRetries=3}, bulkOptions=BulkOptions{asyncMutatorCount=2, useBulkApi=true, bulkMaxKeyCount=125, bulkMaxRequestSize=1048576, autoflushMs=0, maxInflightRpcs=160, maxMemory=90072678, enableBulkMutationThrottling=false, bulkMutationRpcTargetMs=100}, callOptionsConfig=CallOptionsConfig{useTimeout=false, shortRpcTimeoutMs=60000, longRpcTimeoutMs=600000}, usePlaintextNegotiation=true}.
Mar 28, 2018 9:36:51 AM com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation info
INFO: Retrying failed call. Failure #1, got: Status{code=UNAVAILABLE, description=io exception, cause=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:41673
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	... 11 more
} on channel 16

**Comment by sduskis** [comment]
@igorbernstein2, I think we need some help here.  Do you have any idea why the app profile id test is failing here?

**Comment by igorbernstein2** [comment]
I'm guessing it has something to do with having 2 BigtableSessions. I can debug it in the next couple of days

**Comment by sduskis** [comment]
@rupeshitpatekarq, I'm going to close this pull request, and work on a different version of this functionality.  Thanks for all of your work; the investigation work that you did was invaluable in making this feature a reality.

**Pull request closed without merging**
